# Generated by Django 3.2.8 on 2022-07-20 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='Im an User', max_length=256, verbose_name='bio')),
                ('avatar', models.ImageField(null=True, upload_to='imagenes/avatars', verbose_name='avatar')),
                ('departamento', models.CharField(choices=[('AC', 'Atencion_al_Cliente'), ('Inv', 'Inventarios'), ('Ven', 'Ventas'), ('Ad', 'Admin')], max_length=32, verbose_name='department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
