# Generated by Django 3.2.8 on 2022-08-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portada_perfil',
            field=models.ImageField(null=True, upload_to='imagenes/portada', verbose_name='portada'),
        ),
    ]
